### ISSUE TITLE
One Loop wants to be reinstalled each time it's run

### ISSUE THREAD

**Issue by TheBismarck** [carlashley/appleloops#22]
**Describe the bug**
One of the loops keeps reinstalling over and over again each time the script it run. The script itself runs perfectly fine and no error is produced, just that each time, one of the 700-odd loop packages wants to keep reinstalling... The loop package is named: "MAContent10_AssetPack_0796_DemosongLogicoceaneyes.pkg"

The reason this is an issue is that in our deployment, I run a launchd script at 1am each morning on our lab machines to install all the loops... The idea being is that if Apple update Logic as they do, then my server will download any new loops to our LAN-side webserver automatically, which the workstations all look to to pull down the loops. Works really well, and the above issue isn't really a big problem, but just curious as to just why it's this package... I've tried deleting my entire webserver of loops and re-downloading all 70Gb again... same issue.

**Version**
3.16

**Command Used**
/usr/local/bin/appleloops --deployment --pkg-server http://server.domain.com/custom/appleloops -m -o --allow-untrusted

**Debug Log**
Let me know if you still require this as no error is produced.

**Screenshots**

**Comment by carlashley** [comment]
Yes, the debug log is required.

**Comment by carlashley** [comment]
This issue appears to be caused by Apple incorrectly referencing a file path used to determine if the loop is installed.

Examining the `FilePath` check of `logicpro1050.plist` for the `MAContent10_AssetPack_0796_DemosongLogicoceaneyes` package yields a value of `/Library/Application Support/Logic/Logic Pro X Demosongs/ocean eyes.logicx/Alternatives/000/DisplayState.plist`.

Examining the actual packge for the file path contents indicates the file should be found here:
`/Library/Application Support/Logic/Logic Pro X Demosongs/ocean eyes.logicx/Alternatives/001/DisplayState.plist`.
