### ISSUE TITLE
Not all loops installed for fresh install of GarageBand 10.3.2; Logic Pro 10.4.5 using this script

### ISSUE THREAD

**Issue by blackholemac** [carlashley/appleloops#45]
- Command used: /usr/local/bin/appleLoops.py --deployment --mandatory-only --optional-only --mute-progress-bar

- Version: 2.2.3

- Debug log output: I did not run this in debug mode, but you are more than welcome to my lengthy console log.

I am guessing things got changed up by the new Logic Pro 10.4.5 release. I can see that Apple tweaked /Applications/Logic Pro X.app/Resources/logicpro1042.plist file as it has a June 11, 2019 modification date.

**Comment by carlashley** [comment]
Hey @blackholemac thanks for filing this issue. Posting a debug log will be very helpful to investigate why you're not getting all the loops deployed.

Also, if there are any install errors, the `installer` tool logs to `/var/log/install.log` - there may be some evidence in there as to why some packages fail to install.

There are a number of packages that will fail to deploy on versions of GarageBand that use the loops source `garageband1021.plist`. This may also now happen with Logic Pro X. The debug log would help me determine if this was the case.

I have also just patched issue #44 which may potentially be an issue.

**Comment by dad-attitude** [comment]
Hey carlashley,

I'm noticing the same issue. After running Appleloops mandatory deployment Garageband still wants to download about 310.3 MB of sound packs. Logic Pro works great. I ran the command below, then ran it in debug mode and am including the log below.

command used `/usr/local/bin/appleloops.py --deployment -m`

version 2.2.4

[appleLoops.log](https://github.com/carlashley/appleLoops/files/3350788/appleLoops.log)

I did check the install.log you mentioned but I'm too much of a newb to figure out what that should be telling me. I was able to capture a list of the sound packs GarageBand attempts to install after running this version of the script. I'm including that below. The first item is the folder name where they are found.

> lp10_ms3_content_2016
> MAContent10_AssetPack_0358_EXS_BassElectricFingerStyle.pkg
> MAContent10_AssetPack_0358_EXS_BassElectricFingerStyle.pkg.resumeDataMA
> MAContent10_AssetPack_0482_EXS_OrchWoodwindAltoSax.pkg
> MAContent10_AssetPack_0482_EXS_OrchWoodwindAltoSax.pkg.resumeDataMA
> MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg
> MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg.resumeDataMA
> MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg
> MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg.resumeDataMA
> MAContent10_AssetPack_0491_EXS_OrchBrass.pkg
> MAContent10_AssetPack_0491_EXS_OrchBrass.pkg.resumeDataMA

Thanks a ton and let me know if you need further info.

**Comment by apizz** [comment]
This is just to chime in and say that we are _not_ having issues.  Deployed latest GarageBand mandatory and optional loops with appleLoops 2.2.3 last week on a machine running and 10.13.6 GB launched without issue via `--deployment`.

To be clear, about a month or two ago I did a full redownload of all available loops from Apple to our local package server, so we are not doing the deployment direct with Apple.

**Comment by carlashley** [comment]
@dad-attitude @blackholemac - just adding to @apizz comments, if you're using a local HTTP mirror, then you will occasionally need to "refresh" that local HTTP mirror as while the package names may not technically change, the content _might_ change, which presently is something that `appleloops` doesn't know about.

[I do recommend re-downloading the loops and updating the local HTTP mirror](https://github.com/carlashley/appleloops/wiki/Local-Mirror-Deployment) if that's how you're deploying them.

I'm also still not entirely sure how to go about handling those scenarios where GarageBand attempts to install packages after they've been deployed by `appleloops`. I'm currently working on `python3` compatibility, and I'm adding in not just a Bundle ID check, but also using the file check that Apple has in their `PLIST` file as additional criteria. Ultimately though, until Apple provide a `shasum` of the package in the `PLIST` file, or I finally figure out what the big data blob is in the `PLIST`, then this issue is likely to occasionally pop up.

**Comment by crawlgsx** [comment]
Wanted to pop in and state I am new to apple Loops but having the same issue with GarageBand still persisting to want to download the ~310mb of files requiring admin. I have tested this on 10 of my 900 machines so far and every single one is doing it. I am at a loss for getting by this. 

Using Jamf self service to install Garageband App, followed immediately by using appleloops before opening the app. 

Command used : `/usr/bin/python /tmp/appleLoops-master/appleLoops.py --deployment --mandatory-only`

As soon as the app is opened it starts downloading the files and then prompts for Admin when finished.  No local HTTP.

**Comment by JCSmillie** [comment]
I was having a very similar situation.  MacOS 10.14.6 and GB 10.3.2.  I deploy GB through munki and run appleloops.py as a post install script with munki.  Maybe two months ago I tried using this deployment method, a ton of stuff would install, but when I opened GB it still wanted to install more.  I got preoccupied and didn't get back to looking at why until now.  When I run Appleloops.py I export my log to a special place.  Went into that log and saw a certain package was failing.  Went to the munki server I had holding the packages Appleloops previously downloaded. deleted that package (in my case it was MAContent10_AssetPack_0004_AlchemyWoodwinds.pkg,) let Appleloops.py check for stuff again.  Then I went back to my test machine.  This time the package in question installed and a bunch of stuff installed afterwards.  Can't replicate the problem now.

So FWIW if you have any packages in your appleloops.py log file that are failing you may want to just delete those off your cache server and download them again.

**Comment by crawlgsx** [comment]
@JCSmillie unfortunately no caching server here but same problem :-/

**Comment by crawlgsx** [comment]
Wanted to update:

If I do a download with AppleLoops instead of deploy, and install using a script (pkg installer * on the optional folder) then it works fine. No missing loops and Garageband is fine, no prompt.

**Comment by Ottwalker** [comment]
Running the latest release of apple loops and Garageband 10.3.2 on OS 10.14.6.  Everything worked perfectly using a caching server until recently.  I've tried resetting my caching server content and pulling down a new copy of the loops to it but after re-imaging it still wants to install the additional 300 ish Mbs of loops.  I then downloaded a local copy of the loops and stuck it on my munki server and pointed test clients to it.  Same result.  I see above a mention of issues when using the garageband1021.plist.  Is there a reason the latest 10.3.2 of Garageband has this old .plist file under the /Contents/Resources/ of the app and not one that is the same version? Maybe i'm missing something obvious.

**Comment by crawlgsx** [comment]
@Ottwalker I was able to package the 376mb of missing soundloops I listed above, in conjunction with using AppleLoops. Doing this I no longer am seeing the prompt to download or need for admin.

**Comment by carlashley** [comment]
Hey all,

I'm not really in the Mac admin game these days so I'm sorry it takes a while to get back to these issues.

I  have been working on making this `python3` compatable and in the process I've noticed that there's some odd behaviour under certain circumstances.

Can @crawlgsx, @Ottwalker, @JCSmillie confirm if you're _only_ deploying for a single app, or are you deploying for a combination of apps? For example, only deploying GarageBand, or deploying GarageBand + Logic Pro X (or other variation).

I do also need to point out that there are times Apple will update a specific package on the `audiocontentdownload` servers, that will have the same file names and package ID's as existing versions, which can trip the `appleloops.py` up, and currently I have no real solution to this. The only recommendation I have is to remove the loops from any HTTP mirror you're using and update them, or if you're pulling them through a Caching Server, either purge the Caching Server or don't use the Caching Server (I personally would recommend using a HTTP mirror where you can because this way you don't need to purge ALL the content of your Caching Server).

@Ottwalker re the comment about the latest GarageBand version having a `garageband1021.plist` file in the `Contents/Resources` folder - this file appears to only change when Apple introduces entirely new loops/content, or removes old loops/content, and it seems to only be used as a _fallback_ if the same file is accessible from their `audiocontentdownload` servers.

In the `python3` version, I'm using not just the bundle ID of the package, but also the file check details that are in the `plist` files supplied by Apple, this may potentially solve this problem of some content not always updating, but I can't tell just yet.

**Comment by Ottwalker** [comment]
For me I am only deploying Garageband.  I've tried purging my caching server as well as downloading a copy and sticking it on my munki server and pointing clients to it.  Both of those resulted in the issue we are talking about.  In the end I took @crawlgsx advice.  I downloaded all optional loops and then grabbed the 7 loops he mentioned and imported them into munki.  Tested yesterday and the issue is gone.  @carlashley thanks for all your work on this utility.  Its a great help and much appreciated.

**Comment by crawlgsx** [comment]
@carlashley  Appreciate the response, no worries we definitely get it and appreciate all of your efforts!! I am only deploying GarageBand

I do not use a mirror or caching server so unfortunately nothing I can try as far as deleting files.

**Comment by carlashley** [comment]
@crawlgsx @Ottwalker @JCSmillie @dad-attitude @blackholemac 
I may have a fix in commit https://github.com/carlashley/appleloops/commit/c57a85b9dff961cf14ddbcee13c744633729f4ea - if you're in a position to run a test on a machine and let me know how that goes it would be much appreciated.

**Comment by Ottwalker** [comment]
I used the updated appleloops.py today on a couple of test machines and unfortunately it is doing the same thing.  I even wiped out my caching server again before re-imaging the last test machine but it was still asking for the additional loops afterwards.

**Comment by carlashley** [comment]
Thanks @Ottwalker - after further digging around the issue is caused by the Apple "mirrors" of the plist files that are stored locally not being updated. I've filed feedback with Apple and I'm applying a bodge of a patch in https://github.com/carlashley/appleloops/commit/4213aa6fc199fbb75840a77347d203ffe221d699 to get around this issue.

The issue specifically is that the local version of `garageband1021.plist` had the `IsMandatory` flag set to `<true/>` for several packages, but the version on `audiocontentdownload.apple.com` has it set to `<false/>`.

The next major release of this tool is going to switch over to using the local files as the reference point for what packages are downloaded etc.

When you have a chance, try the 2.2.6 version and see if that resolves the issue.

If others have similar issues with Logic Pro X/MainStage, would be interested to know.

**Comment by Ottwalker** [comment]
Thanks for your time on this.  I'm away from work for a week now but I'll test it out as soon as i'm back if no one beats me to it.

**Comment by dad-attitude** [comment]
Hey @carlashley thanks again for all you've done with this. I was able to run the 2.2.6 version today and instead of a 310 MB download I only had one 50MB download for mandatory Garageband loops. It appears the package in question was  `MAContent10_AssetPack_0509_EXS_StringEnsemble.pkg`

command used `/usr/local/bin/appleloops.py --deployment -m`

version 2.2.6

Fresh install of MacOS 10.14.5 and GarageBand 10.3.2

We are not using a cache/local mirror as I do not have access to servers so I'm just pushing/running the script and letting them download from Apple.

**Comment by Jet-Jaguar** [comment]
@carlashley- thanks for working on this but unfortunately still requiring admin credentials,  in addition to not downloading all the loops.

**Comment by carlashley** [comment]
@dad-attitude My bad, it turns out it was a typo in the filename.

@dad-attitude @Jet-Jaguar Check if 2.2.7 resolves this.

**Comment by dad-attitude** [comment]
Tested 2.2.7 this morning with Garageband and Logic on Mojave 10.14.6 fresh install and it is working! Thanks again for all your work on this!

command used `/usr/local/bin/appleloops.py --deployment -m`

**Comment by carlashley** [comment]
wOOt :)

**Comment by jrouthier** [comment]
Can confirm that 2.2.7 works for me, where 2.2.6 was giving me about 367MB worth of loops to still install. Thank you for your great work @carlashley
